-- ==========================================
-- STEP 1: Enable the pgvector extension (if not already enabled)
-- ==========================================
create extension if not exists vector;

-- ==========================================
-- STEP 2: Create the ai_act table
-- ==========================================
CREATE TABLE IF NOT EXISTS public.ai_act (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text UNIQUE NOT NULL,
  pillar text NOT NULL, -- EU AI Act risk category (e.g. PROHIBITED PRACTICE, HIGH RISK, LIMITED RISK, MINIMAL RISK)
  title text NOT NULL,
  human_summary text NOT NULL, -- Holds full article text
  verdict text NOT NULL, -- Holds compliance requirements verdict
  risk_level text NOT NULL, -- critical, warning, stable
  source_url text DEFAULT 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024R1689',
  source_type text DEFAULT 'regulation',
  paper_year int DEFAULT 2024,
  authors text DEFAULT 'European Parliament & Council',
  is_premium boolean DEFAULT false,
  embedding vector(768),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==========================================
-- STEP 3: Create Full Text Search (FTS) generated column and indices
-- ==========================================
ALTER TABLE public.ai_act DROP COLUMN IF EXISTS fts;
ALTER TABLE public.ai_act ADD COLUMN fts tsvector GENERATED ALWAYS AS (
  to_tsvector('english', coalesce(title, '') || ' ' || coalesce(human_summary, '') || ' ' || coalesce(verdict, ''))
) STORED;

CREATE INDEX IF NOT EXISTS ai_act_fts_idx ON public.ai_act USING gin(fts);
CREATE INDEX IF NOT EXISTS ai_act_embedding_idx ON public.ai_act USING hnsw (embedding vector_cosine_ops);

-- ==========================================
-- STEP 4: Setup Row Level Security (RLS) policies
-- ==========================================
ALTER TABLE public.ai_act ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to ai_act" 
ON public.ai_act FOR SELECT 
TO public 
USING (true);

-- ==========================================
-- STEP 5: Create the hybrid_search_ai_act RPC function
-- ==========================================
CREATE OR REPLACE FUNCTION public.hybrid_search_ai_act(
  query_embedding vector(768),
  query_text text,
  match_limit int,
  filter_category text default null
)
RETURNS TABLE (
  id bigint, code text, pillar text, title text, human_summary text,
  metric text, verdict text, risk_level text, source_url text, source_type text,
  paper_year int, authors text, is_premium boolean,
  similarity_score float, keyword_score float, combined_score float
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    a.id, a.code, a.pillar, a.title, a.human_summary, 
    'Compliance Checklist'::text as metric, 
    a.verdict, a.risk_level, a.source_url, a.source_type, 
    a.paper_year, a.authors, a.is_premium,
    COALESCE(1.0 - (a.embedding <=> query_embedding), 0.0)::float as similarity_score,
    ts_rank_cd(a.fts, plainto_tsquery('english', query_text))::float as keyword_score,
    (
      CASE 
        WHEN a.embedding IS NULL THEN ts_rank_cd(a.fts, plainto_tsquery('english', query_text))::float
        ELSE (COALESCE(1.0 - (a.embedding <=> query_embedding), 0.0)::float * 0.8) + 
             (LEAST(ts_rank_cd(a.fts, plainto_tsquery('english', query_text))::float, 1.0) * 0.2)
      END
    )::float as combined_score
  FROM public.ai_act a
  WHERE 
    (filter_category IS NULL OR a.pillar = filter_category) AND
    (
      (a.embedding IS NOT NULL) OR 
      (a.fts @@ plainto_tsquery('english', query_text)) OR
      (query_text = '')
    )
  ORDER BY combined_score DESC
  LIMIT match_limit;
END;
$$;
